### ISSUE TITLE
Conversations being duplicated

### ISSUE THREAD

**Issue by 4rsenal** [klinker-apps/messenger-issues#26]
So for pretty much every convo I have interacted with throught this app there are multiple conversations. Some of the conversations are just several of only my outgoing while some are both outgoing and incoming. Also it seems none of the messages repeat, whatever convo they are in there is no copy. Also, group text split up into 2 convos, one convo is everything I sent the other is everything I received.
[2ManyConvos.txt](https://github.com/klinker-apps/messenger-issues/files/443868/2ManyConvos.txt)
![screenshot_20160829-220828](https://cloud.githubusercontent.com/assets/21323005/18073644/acc4d140-6e35-11e6-90dc-8fbc039a4f3f.png)

**Comment by ddechant** [comment]
Some of my conversations have been moved over 10x. I think this may be due multiple logins or signups. On my Note 4 I didn't really get an indication that any data was being transferred until I realized that I had some additional notification in my notification bar.

**Comment by klinker41** [comment]
I would agree that could contribute to the problem, but not positive. I would go into the "my account" section and click on the remove account option, then clear the app data and sign up again.

**Comment by ddechant** [comment]
I tried 😄  #29

**Comment by klinker24** [comment]
As a note, I saw something similar this morning. 

**Steps to Reproduce:**

1. Clear the app data
2. Open the app again and you are presented with the sign in screen
3. Instead of creating a new account, sign in to one that has been previously created.
4. After the sign in, it seems to both bring in your messages that are saved in the device's internal content provider, as well as bring in the messages from the cloud. So you have two copies of the same

**Comment by klinker41** [comment]
If you sign into an account, your internal messages will not be brought in. 

I saw this happen once when I received a message while the optimization process was occurring.

**Comment by klinker41** [comment]
Made some changes to this inside the database, `id_matcher` (which is used to identify a conversation) is now a `unique` column meaning that if the app tries to insert a conversation with the same `id_matcher` as already exists, it won't allow that to happen.

Changes couldn't be made for existing users, anyone who wants this will need to clear the app data and sign in again. It will be active for any new installs however.

Leaving this issue open to watch it for a while, but this should be fixed (although other issues might come out of it).

**Comment by klinker41** [comment]
also made some changes on the server to prevent this situation, should be fixed now for new users: https://github.com/klinker41/messenger-server/commit/3bf05e3c18386965c108fc30a2b9181b4c1b5397

**Comment by jwkicklighter** [comment]
Still having this issue, tried clearing data and relogging. Nexus 6 on Nougat Preview 5.

Can't seem to find any pattern to the conversations that are duplicated, but it isn't every one.

**Comment by klinker41** [comment]
made a few changes recently that might hide this problem from the ui at least in the future https://github.com/klinker41/messenger-web/commit/ad077e2a0d579c15052d209f3e7667b1cdda3044
