### ISSUE TITLE
Incorrect name for unregistered number

### ISSUE THREAD

**Issue by codewalk3r** [klinker-apps/messenger-issues#366]
**Device with issue:** Samsung J7 SM-G610Y
**Primary device:** Samsung J7 (2017) on Android 6.0.1
**App version:** 2.4.1.1307
**Steps to reproduce:**

1. Receive SMS

**Additional information:**

SMS from network/operator (uses short number like 4438 or just TM) displays incorrect contact name from phone book. Numbers aren't really registered since it could just be status updates from network or even SPAM but Pulse app incorrectly guesses the display name for an unregistered number.

**Comment by klinker24** [comment]
I have had a few reports of this. I changed some things for the latest version, and I think I am just going to roll back those changes. Thanks for the report on this

**Comment by lalibi** [comment]
I have a simiral issue and these two are possibly related. I haven't opened a new issue (not yet at least), since I think this info will be more helpful here.

When I get an SMS from my mobile provider (Vodafone GR), the message thread is incorrectly matched with one of two specific contacts I have in my address book. **Those two contacts both happen to work for the provider mentioned**.

I assume that the app tries to match the `Company` field of those two contacts (both have "Vodafone Greece" in this field), with the `Phone Number` of the received message (it shows as "Vodafone" in `Conversation Information`. 

I tried to test this assumption, by changing the `Company` field in one of those two contacts, but the matching didn't change. I seems that this matching is persistent.

**Comment by klinker24** [comment]
@lalibi yes they are related. This has been fixed in the current version, but it will not affect conversations that are already in the database. You can clear the app data to refresh those titles, or delete the conversation and it will show correctly the next time a message comes in.

**Comment by lalibi** [comment]
Unfortunately, this issue wasn't resolved for me. I tried clearing the app data, I even uninstalled and re-installed the app but to no avail.

In one case, where I received a message from my bank, the name displayed is from one of my contacts, that works for that bank, and the profile photo is from a third contact, also working in the same bank!

I am using version v2.4.6.1355.
