### ISSUE TITLE
No Chrome notifications

### ISSUE THREAD

**Issue by kakawait** [klinker-apps/messenger-issues#379]
**Device with issue:** MacBook Pro El Capitan 10.11.6 
**Chrome version:** 59.0.3071.115 (Official Build) (64-bit)
**Primary device:** OnePlus One with custom ROM Ressurection Remix (Android Nougat 7.1)
**App version:** 2.4.4.1328
**Steps to reproduce:** 

1. Using the extension
2. Ask someone to send you a sms 

I get notification on my phone but nothing on the desktop.

**Comment by klinker24** [comment]
The web will not notify you. The extension and app should. Thanks for the report

**Comment by kakawait** [comment]
I'm using this app https://chrome.google.com/webstore/detail/pulse-extension/jjbjdleccaiklfpcblgekgmjadjdclkp (just installed this morning) but no notification.

When I tested I got both chrome tab and extension!

**Comment by klinker24** [comment]
Yes I know what app you mean. I don't have a solution for this at this time, sorry

**Comment by kakawait** [comment]
@klinker24 Yeah no prob I can wait. I just bought PulseSMS 3 days ago and I used basic sms app without desktop support for many years so I can wait :)

**Comment by klinker24** [comment]
I pushed up some changes to this. If you use the "re-register for notifications" option in that screenshot, does it work? If not, can you open up the web app, go to *My Account* then *Devices* and see if the extension shows up there?

**Comment by kakawait** [comment]
@klinker24 I did "re-register for notifications" but issue still the same.

On _Devices_ pages I only see my phone

![screen shot 2017-07-18 at 12 59 43](https://user-images.githubusercontent.com/275609/28313959-12221ddc-6bb9-11e7-8258-1bb018791da4.png)

**Comment by kakawait** [comment]
@klinker24 Is working now. I don't think I did something but I can see extension to be part of _Devices_ and notifications are working
