### ISSUE TITLE
Add spellcheck

### ISSUE THREAD

**Issue by thatchrismiller** [klinker-apps/messenger-issues#470]
**Device with issue:** MacBook Pro (Retina, 13-inch, Early 2015) with macOS 10.12.6
**Primary device:** LG G6 (Sprint) with Android 7.0
**App version:** 2.5.6.1546
**Steps to reproduce:**

1. Open Mac App (beta)
2. Click in text box and type misspelled word
3. Built-in spellcheck is disabled for this text box.

**Possible solution:**
Activate spellcheck for app. (Usually appears in Edit menu, but is missing in Pulse.)

**Comment by klinker24** [comment]
Thanks, will add spell checking in the future.

---

https://github.com/electron-userland/electron-spellchecker/blob/master/example/preload.js

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-chrome/commit/34403776aae65a41ba3080b78ec3d8125d7d17b8

**Comment by thatchrismiller** [comment]
I hate to bring this back up, but I am running the latest version on Mac and still not seeing the spellcheck option.

**Comment by klinker24** [comment]
Seems like it wasn't applied to the production releases. Hmm.

**Comment by klinker24** [comment]
Ok, verified this time: https://github.com/klinker41/messenger-chrome/commit/d8e3f8d70ed747f0b052cae751cd5f03f7e5689c
