### ISSUE TITLE
No notifications, no refresh of the overview

### ISSUE THREAD

**Issue by JariVanBoven** [klinker-apps/messenger-issues#506]
**Device with issue:** Windows 10 latest version
**Primary device:** OnePlus 3T
**App version:** 2.6.2.1726
**Steps to reproduce:**

1. Install latest version of Windows client
2. I don't receive any notification and the message overview doesn't refresh automatically.

Already tried to delete and reinstall but the problem exist.
Already tried to restore my account but it didn't help.

**Comment by klinker24** [comment]
Please be more specific in what you mean by "overview". Is that just the conversation list, or does it not automatically update the message lists either

Please be more specific in what you mean by "restore my account". Logging out and back in will not change anything, ever. The web/desktop clients simply access the backend, logging out and back in will not change what is available on the backend.

**Comment by JariVanBoven** [comment]
Hi 

Sorry, hereby the missing information:
- With overview I mean the conversation list. When I open a conversation, new messages are shown intantly without a refresh of the page. But when I'm at the conversation list, I don't see it when I receive a new message. It doens't refresh and doesn't generate a notification.
- I went to the Pulse app on Android > Account > Refresh Account. 

Hope this helps.

**Comment by klinker24** [comment]
If you are on the web version of the app, does the conversation list refresh automatically there?

I would imagine that your computer is shutting down the background connections for apps that are you are not interacting with. This would affect notifications, and the conversation list refresh, if it is just sitting there on your screen.

If that is the case, there won't be anything I can do on my end, you will need to go through your computers power settings and see what you can find.

**Comment by JariVanBoven** [comment]
Any idea where I can find that settting in Windows?

Yes, the web works like it should.

But I tried the following:
- Close ALL programms and open only Pulse on my pc
- Make Pulse active window
- Send text
- The conversation list still doesn't refresh

**Comment by klinker24** [comment]
It seems very unlikely to me that the message lists would be updating automatically when the conversation list isn't. They run off of the same services. It might be helpful to make a video to demonstrate this issue.

The desktop app is just a wrapper for the web app. If the web is working as expected, then I am pretty confident saying that this issue is with power management or background services.

**Comment by JariVanBoven** [comment]
I've send you an email with the video.

**Comment by JariVanBoven** [comment]
I also don't receive a notification when using Firefox and there the conversation list also doesn't refresh automatically.

**Comment by klinker24** [comment]
I am not able to reproduce this issue on the desktop apps, chrome, or firefox.

If you open firefox, right click the page, hit "inspect", then go to the console tab, does it show any errors

**Comment by klinker24** [comment]
Actually, I think I just fixed that issue. I just deployed the changes, you will need to invalidate the web cache to see them, or just wait awhile for your browser to do it for you.

**Comment by JariVanBoven** [comment]
Nice! The conversation list refreshes again and I receive a notification in Firefox. BUT I still don't receive a Windows notification....

**Comment by klinker24** [comment]
I will direct you back to the power setting that I originally told you about. The windows app wouldn't have downloaded any of the changes yet anyways.
